@Swagger_Use_HostAddress = https://localhost:7065


GET {{Swagger_Use_HostAddress}}/api/products

###




GET {{Swagger_Use_HostAddress}}/api/products

###

POST {{Swagger_Use_HostAddress}}/api/products
Content-Type: application/json

{
  //Product
}

###

GET {{Swagger_Use_HostAddress}}/api/Products/1

###

GET {{Swagger_Use_HostAddress}}/api/products/1

###

DELETE {{Swagger_Use_HostAddress}}/api/products/2

###

PUT {{Swagger_Use_HostAddress}}/api/products/0
Content-Type: application/json

{
  //Product
}

###

GET {{Swagger_Use_HostAddress}}/api/products/search?name=Pro

###
